---
AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS Sample Template that specifies a server with volumes and two users."
  

Metadata:
  Instances: 1
    Description:"Amazon Linux 2 AMI (HVM), SSD Volume Type"
Parameters:
  InstanceTypeParameter: 
    Type: amzn2
    Default: t2.micro

Mappings: 
  RegionMap: 
    us-east-1: 
      "HVM64": "ami-0ff8a91507f77f867"

Resources:
   volumes:
    - device: /dev/xvda
      size_gb: 10
      type: ext4
      mount: /
    - device: /dev/xvdf
      size_gb: 100
      type: xfs
      mount: /data

Outputs:
  set of outputs